### ISSUE TITLE
Rake failing on Linux

### ISSUE THREAD

**Issue by duncan-bayne** [duncan-bayne/bigpond-downloader#1]
Currently, compilation is failing on Ubuntu Linux running CoffeeScript 1.1.2:

```
duncan@duncan-notebook:~/bigpond-downloader$ rake
Error: In userscript.js, too many ) on line 76
    at Error (unknown source)
    at Rewriter.ensureBalance (/usr/local/lib/node_modules/coffee-script/lib/rewriter.js:286:19)
    at Rewriter.rewrite (/usr/local/lib/node_modules/coffee-script/lib/rewriter.js:21:12)
    at Lexer.tokenize (/usr/local/lib/node_modules/coffee-script/lib/lexer.js:37:29)
    at Object.compile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script.js:29:34)
    at /usr/local/lib/node_modules/coffee-script/lib/command.js:149:33
    at /usr/local/lib/node_modules/coffee-script/lib/command.js:187:12
    at /usr/local/lib/node_modules/coffee-script/lib/command.js:112:28
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
rake aborted!
uncaught throw "Failed to compile CoffeeScript."

Tasks: TOP => default => build
(See full trace by running task with --trace)
```

The following Gems are installed:
- bundler (1.0.18)
- coffee-script (2.2.0)
- coffee-script-source (1.2.0)
- execjs (1.2.13)
- hike (1.2.1)
- jasmine-core (1.1.0)
- jasmine-headless-webkit (0.8.4)
- multi_json (1.0.4)
- rack (1.4.0)
- rainbow (1.1.3)
- rake (0.9.2)
- sprockets (2.2.0)
- tilt (1.3.3)

**Comment by duncan-bayne** [comment]
Closing this; have moved repo to GitLab.
